- hosts: localhost
  gather_facts: False
  vars:
    username: demo
    password: R3dh4t1!
  tasks:
  - name: "Get the FrontEnd URL"
    command: "oc get route rhmap --template \"https://{{ '{{' }}.spec.host{{ '}}'}}\" --namespace {{ rhmap_project_core }}"
    register: frontend_url

  - name: "Get the FrontEnd's Username"
    command: "oc get dc/millicore --output jsonpath='{{ '{' }}.spec.template.spec.containers[*].env[?(@.name==\"FH_ADMIN_USER_NAME\")].value{{ '}' }}' --namespace {{ rhmap_project_core }}"
    register: frontend_username

  - name: "Get the FrontEnd's Password"
    command: "oc get dc/millicore --output jsonpath='{{ '{' }}.spec.template.spec.containers[*].env[?(@.name==\"FH_ADMIN_USER_PASSWORD\")].value{{ '}' }}' --namespace {{ rhmap_project_core }}"
    register: frontend_password

  - set_fact: rhmap_url={{ frontend_url.stdout }}
  - set_fact: rhmap_username={{ frontend_username.stdout }}
  - set_fact: rhmap_password={{ frontend_password.stdout }}

  - name: Set RHMAP Target
    command: fhc target {{ rhmap_url }}

  - name: Login as username{{ ':' }} {{ rhmap_username }}  password{{ ':' }} {{ rhmap_password }}
    command: fhc login {{ rhmap_username }} {{ rhmap_password }}

  - set_fact: rhmap_newly_user={{ username }}@{{ username }}.com

  - name: Create a demo user
    command: fhc admin-users create username={{ rhmap_newly_user }} password={{ password }} email={{ rhmap_newly_user }} name={{ rhmap_newly_user }} roles=customeradmin,portaladmin,devadmin,dev,analytics
    register: rhmap_create_user

#  - name: Get MBaaS KEY
#    command: "oc get dc/fh-mbaas --output jsonpath='{{ '{' }}.spec.template.spec.containers[*].env[?(@.name==\"FHMBAAS_KEY\")].value{{ '}' }}' --namespace {{ rhmap_project_mbaas }}"
#    register: fh_mbaas_key

#  - name: Get MBaaS URL
#    command: oc get route/mbaas --output jsonpath='https{{ ':' }}//{..spec.host}' --namespace {{ rhmap_project_mbaas }}
#    register: mbaas_url

#  - name: Create a MBaaS Target
#    command: fhc admin mbaas create --id mbaas --url https://{{ openshift_master_hostname }}:8443 --servicekey {{ fh_mbaas_key.stdout }} --routerDNSUrl *.{{ openshift_cloudapps_domain }} --fhMbaasHost {{ mbaas_url.stdout }} --type openshift3

#  - name: Create an Enviroment for this MBaaS Target (PENDING{{ ':' }} FETCH MASTER's TOKEN)
#    command: fhc admin environments create --id demo --label Demo --target mbaas --token v39-XIooljYWPPVCUqbMXpmXYFstjscG8i-ozMSHRpk

  - name: Log as Demo user
    command: fhc login {{ rhmap_newly_user }} {{ password }}

  - name: Create a RHTTravel Project
    command: fhc projects create RedHat-Travel bare_project
    register: project_info

  - set_fact: project_info_object={{ project_info.stdout | from_json }}

  - name: Delete Directory (if does exist)
    file: path=/tmp/fhMobileApp state=absent

  - name: Git clone project{{ ':' }} https{{ ':' }}//github.com/latam-tech-office/fhMobileApp
    command: git clone https://github.com/latam-tech-office/fhMobileApp /tmp/fhMobileApp

  - name: Compact the contents from fhMobileApp
    shell: pushd /tmp/fhMobileApp; zip -r fhMobileApp.zip *; popd

  - name: Delete Directory (if does exist)
    file: path=/tmp/fhCloudApp state=absent

  - name: Git clone project{{ ':' }} https{{ ':' }}//github.com/latam-tech-office/fhCloudApp
    command: git clone https://github.com/latam-tech-office/fhCloudApp /tmp/fhCloudApp

  - name: Compact contents from fhCloudApp
    shell: pushd /tmp/fhCloudApp; zip -r fhCloudApp.zip *; popd

  - name: Import Contents from fhMobileApp into project
    command: fhc import {{ project_info_object.guid }} mobileApp client_hybrid /tmp/fhMobileApp/fhMobileApp.zip

  - name: Import Contents from fhCloudApp into Project
    command: fhc import {{ project_info_object.guid }} cloudApp cloud_nodejs /tmp/fhCloudApp/fhCloudApp.zip --env=demo
