apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-shell-claim
spec:
  accessModes:
  - ReadWriteMany
  - ReadWriteOnce
  resources:
     requests:
       storage: 5Gi
  selector: 
    matchLabels: 
      rhmap_core: gitlab-shell
